[package]
name = "cargo-liquid"
version = "1.0.0-rc3"
authors = ["vita-dounai <lichenxi.webank@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
anyhow = "1.0.32"
structopt = "0.3.16"
heck = "0.3.1"
colored = "2.0.0"
zip = "0.5.6"
cargo_metadata = "0.11.1"
rustc_version = "0.2.3"
cargo-xbuild = "0.6.6"
toml = "0.5.6"
tempfile = "3.1.0"
parity-wasm = "0.41.0"
pwasm-utils = "0.14.0"
which = "4.0.2"
indicatif = { version = "0.15.0", features = ["rayon", "improved_unicode"] }
console = "0.13.0"
env_logger = "*"
log = "*"
log-derive = "*"
petgraph = "0.6"
either = "*"
serde = "*"
serde_json = "*"
itertools = "*"
leb128 = "*"
tiny-keccak = { version = "*", features = ["keccak"] }
libsm = "*"
wabt = "*"

[build-dependencies]
anyhow = "1.0.32"
zip = "0.5.6"
walkdir = "2.3.1"

[[bin]]
name = "cargo-liquid"
path = "src/main/main.rs"

#[[bin]]
#name = "liquid-analy"
#path = "src/analyzer/main.rs"
